### ISSUE TITLE
Unidentified error with Reach Entity Attributes ItemMixin

### ISSUE THREAD

**Issue by eehunter** [Sinytra/ConnectorExtras#28]
### Describe the bug

The ItemMixin from Reach Entity Attributes (Connector Extras implementation) seems to be causing an injection error when used with Spectrum in a development environment.

### Steps to reproduce

1. Clone https://github.com/eehunter/Spectral-Dragons
2. Execute `./gradlew runClient`

### Logs

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method getActualReachDistance(DLnet/minecraft/world/level/Level;Lnet/minecraft/world/entity/player/Player;)D in mixins.reach-entity-attributes.json:ItemMixin from mod reach_entity_attributes failed injection check, (0/4) succeeded. Scanned 1 target(s). Using refmap refmap.reach-entity-attributes.json 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) 	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)

### Additional context

I'm attempting to make a compatibility addon for Spectrum (a Fabric-only mod) and Dragon Survival (a Forge-only mod). When Spectrum is added to the development environment, the above issue occurs. Dragon Survival has been temporarily disabled in the dev environment to help isolate the issue. I have spent 2+ hours trying to debug this will no success, and my knowledge of the inner workings of Mixin and Connector are not sufficient to properly diagnose this. I don't actually know if it's a bug in my buildscript or Connector Extras. I think the former is more likely, but I'm submitting this issue in case the latter is true.

**Comment by eehunter** [comment]
Please disregard, I mistakenly added Connector Extras using `minecraftLibrary` instead of `implementation`.
